project_id = "pkviymixsxwtwrarqomi"

[auth]
enable_signup = false

[functions.create-company]
verify_jwt = true

[functions.invite-user]
verify_jwt = false

[functions.revoke-user-sessions]
verify_jwt = false

[functions.publish-planning]
verify_jwt = true
